IF(OBJECT_ID(N'tempdb..#TMP1118') IS NOT NULL)
	DROP TABLE #TMP1118;

CREATE TABLE #TMP1118
(
	TraceFlag	INT,
	[Status]	TINYINT,
	[Global]	TINYINT,
	[Session]	TINYINT
)

DECLARE @SQL VARCHAR(MAX);
SET @SQL = 'DBCC TRACESTATUS (1118, 1117);'

INSERT INTO #TMP1118
	EXEC (@SQL);

SELECT * 
	FROM #TMP1118 
	ORDER BY TraceFlag

IF(OBJECT_ID(N'tempdb..#TMP1118') IS NOT NULL)
	DROP TABLE #TMP1118;