USE SIGERO_ADMIN
GO
BEGIN

	SET NOCOUNT ON

	IF(OBJECT_ID(N'tempdb..#tmpSpace') IS NOT NULL)
		DROP TABLE #tmpSpace;

	CREATE TABLE #tmpSpace
	(
		[ID] INT IDENTITY(1,1),
		[OBJECTID] BIGINT,
		[SCHEMAID] BIGINT,
		[NAME] VARCHAR(100),
		[ROWS] BIGINT,
		[RESERVED] VARCHAR(100),
		[DATA] VARCHAR(100),
		[INDEX_SIZE] VARCHAR(100),
		[UNUSED] VARCHAR(100),
	)

	CREATE NONCLUSTERED INDEX IX_tmpSpace_1 ON #tmpSpace(ID)

	DECLARE @NAME VARCHAR(100)
	DECLARE @OBJECTID BIGINT
	DECLARE @SCHEMAID BIGINT
	DECLARE @ID INT

	DECLARE CUR CURSOR FOR
		SELECT '[' + SCHEMA_NAME([schema_id]) + '].[' + [name] + ']', [object_id], [schema_id]
			FROM sys.tables 

	OPEN CUR
	FETCH NEXT FROM CUR INTO @NAME, @OBJECTID, @SCHEMAID

	WHILE(@@FETCH_STATUS = 0)
	BEGIN

		INSERT INTO #tmpSpace([NAME], [ROWS], [RESERVED], [DATA], [INDEX_SIZE], [UNUSED])
			EXEC sp_spaceused @NAME

		SET @ID = @@IDENTITY

		UPDATE #tmpSpace 
			SET [OBJECTID] = @OBJECTID, [SCHEMAID] = @SCHEMAID WHERE ID = @ID

		FETCH NEXT FROM CUR INTO @NAME, @OBJECTID, @SCHEMAID

	END

	CLOSE CUR
	DEALLOCATE CUR

	SELECT
			'[' + SCHEMANAME + '].[' + [NAME] + ']' AS TABLENAME,
			[ROWS] AS ROWSCOUNT,
			[DATA] + [INDEX] AS TOTALSIZE,
			[DATA] AS DATASIZE,
			[INDEX] AS INDEXSIZE
		FROM (
			SELECT
					SCHEMA_NAME([SCHEMAID]) AS SCHEMANAME,
					[NAME],
					[ROWS],
					CAST(LEFT([DATA], LEN([DATA]) - 3) AS INT) AS [DATA],
					CAST(LEFT([INDEX_SIZE], LEN([INDEX_SIZE]) - 3) AS INT) AS [INDEX]
				FROM #tmpSpace
			) X
		ORDER BY 3 DESC, 1

	IF(OBJECT_ID(N'tempdb..#tmpSpace') IS NOT NULL)
		DROP TABLE #tmpSpace;

END